# Generated by Django 2.1.7 on 2019-04-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionquestion',
            name='correct_answer',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
