# Generated by Django 2.1.7 on 2019-04-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_sessionquestion_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='subject_code',
            field=models.CharField(default='ECS639U', max_length=10),
            preserve_default=False,
        ),
    ]
