# Generated by Django 2.1.7 on 2019-04-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_session_subject_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-end_time']},
        ),
        migrations.AddField(
            model_name='sessionquestion',
            name='mcq',
            field=models.BooleanField(default=True),
        ),
    ]
