# Generated by Django 2.1.7 on 2019-04-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0005_auto_20190414_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionquestion',
            name='correct_answer',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
