# Generated by Django 2.1.7 on 2019-04-15 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0006_auto_20190414_1835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={},
        ),
    ]
