# Generated by Django 2.1.7 on 2019-04-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0007_auto_20190415_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionquestion',
            name='no_answers',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
