# Generated by Django 2.1.7 on 2019-04-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0008_auto_20190419_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='subject_name',
            field=models.CharField(max_length=60),
        ),
    ]
