# Generated by Django 2.1.7 on 2019-04-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190411_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionchoice',
            name='correct',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
