# Generated by Django 2.1.7 on 2019-04-14 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190412_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionchoice',
            name='correct',
            field=models.BooleanField(default=False),
        ),
    ]
