# Generated by Django 2.1.7 on 2019-04-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190414_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionchoice',
            name='text',
            field=models.CharField(max_length=100, verbose_name='Answer'),
        ),
    ]
