# Generated by Django 2.1.7 on 2019-04-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190419_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='questionchoice',
            name='text',
            field=models.CharField(max_length=150, verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
